sorted envenenada ☠
betrybe/sd-0x-project-algorithms pull request #11
Opened 2021-07-08 00:02 UTC by NicolasFirmo

Uma solução simples para impedir que alunos passem no requisito 3 (Anagramas) usando o _builtin_ `sorted`. Porem ainda não impede que possa ser utilizado o `list.sort`:

> Esse falha
```python
def is_anagram(first_string, second_string):
    return sorted(first_string) == sorted(second_string)
```

> Esse ainda passa =/
```python
def is_anagram(first_string, second_string):
    first_list = list(first_string)
    second_list = list(second_string)
    first_list.sort()
    second_list.sort()
    return ''.join(first_list) == ''.join(second_list)
```

2021-07-08 20:35 UTC, vbuxbaum requested changes

2021-07-08 20:35 UTC, vbuxbaum commented on tests/test_anagrams.py
>      assert is_anagram(first_string, second_string) is False
Gostei da ideia de deixar as duas validações somente numa função, mas pra isso precisamos alterar no arquivo [requirements.json](https://github.com/betrybe/sd-0x-project-algorithms/blob/master/.trybe/requirements.json).

2021-07-09 14:38 UTC, NicolasFirmo commented on tests/test_anagrams.py
>      assert is_anagram(first_string, second_string) is False
Ótimo, esqueci também de atualizar o README

2021-07-13 13:42 UTC, vbuxbaum approved these changes

2021-07-14 13:52 UTC, joaopauloaramuni approved these changes

2021-07-14 13:52 UTC, merged