Update de testes no Req 1
betrybe/sd-0x-project-algorithms pull request #14
Opened 2021-07-27 19:44 UTC by vbuxbaum

2021-07-29 21:03 UTC, barraponto requested changes

2021-07-29 21:03 UTC, barraponto commented on tests/test_study_schedule.py
> -    assert study_schedule(permanence_periods, 5) == 1
Por que essas checagens foram removidas?

2021-07-30 12:46 UTC, vbuxbaum commented on tests/test_study_schedule.py
> -    assert study_schedule(permanence_periods, 5) == 1
Ei @barraponto! 

Essa validação de "_melhor horário empata com a maior saída_" não faz sentido no contexto do requisito (parece que em 2020 esse requisito tinha um contexto um pouco diferente e ficamos com esses resquícios).

O requisito apenas pede que a função desenvolvida retorne quantas pessoas estão presentes em um horário específico (`target_time`). Essa checkagem que foi removida é apenas mais um caso de teste para a validação feita na função anterior (`test_validar_melhor_horario_com_sucesso`), mas que não valida nada diferente.

2021-07-30 21:10 UTC, barraponto approved these changes

2021-08-04 00:23 UTC, joaogallo approved these changes

2021-08-04 12:57 UTC, merged